from JAModel import *

M,H=readcsv("data.csv")
metal=JAModel()
metal.fit(H,M,iterate=30)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=30,autoscale=False,step=0.02)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=20,autoscale=False,step=0.01)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=20,autoscale=False,step=0.01)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=20,autoscale=False,step=0.002)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=20,autoscale=False,step=0.0005)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
metal.fit(H,M,iterate=20,autoscale=False,step=0.0001)
plt.plot(M);plt.plot(metal.predict(H));plot.show()
pM = metal.predict(H)
sM = "\n".join(map(str,pM))
f=open("M_predicted.txt",'w')
f.write(sM)
f.close()